export type AuditCategory =
  | 'AUTH'
  | 'CLIENT'
  | 'NOTE'
  | 'DOCUMENT'
  | 'CONTRACT'
  | 'CONSENT'
  | 'APPOINTMENT'
  | 'ASSESSMENT'
  | 'REPORT'
  | 'INVOICE'
  | 'SETTINGS'
  | 'SECURITY'
  | 'AI'
  | 'EXPORT'
  | 'DELETE'
  | 'SYSTEM'

export type AuditSeverity = 'INFO' | 'WARNING' | 'CRITICAL'
export type AuditStatus = 'SUCCESS' | 'FAILED'

export type AuditAction =
  | 'CLIENT_VIEWED'
  | 'CLIENT_CREATED'
  | 'CLIENT_UPDATED'
  | 'CLIENT_ARCHIVED'
  | 'CLIENT_ANONYMIZED'
  | 'CLIENT_DELETED'
  | 'CLIENT_EXPORTED'
  | 'NOTE_CREATED'
  | 'NOTE_UPDATED'
  | 'NOTE_DECRYPTED'
  | 'NOTE_EXPORTED'
  | 'NOTE_DELETED'
  | 'AI_SUMMARY_GENERATED'
  | 'AI_SUMMARY_GENERATED_FROM_NOTE'
  | 'DOCUMENT_UPLOADED'
  | 'DOCUMENT_VIEWED'
  | 'DOCUMENT_DOWNLOADED'
  | 'DOCUMENT_DELETED'
  | 'DOCUMENT_SHARED'
  | 'DOCUMENT_SIGNED'
  | 'DOCUMENT_VERSION_CREATED'
  | 'CONTRACT_PREVIEWED'
  | 'CONTRACT_ISSUED'
  | 'CONTRACT_DOWNLOADED'
  | 'CONTRACT_UPLOADED_TO_DRIVE'
  | 'CONTRACT_CANCELLED'
  | 'CONTRACT_REGENERATED'
  | 'CONSENT_CREATED'
  | 'CONSENT_VIEWED'
  | 'CONSENT_ACCEPTED'
  | 'CONSENT_REVOKED'
  | 'CONSENT_VERSION_UPDATED'
  | 'CONSENT_PDF_GENERATED'
  | 'ONBOARDING_LINK_CREATED'
  | 'ONBOARDING_LINK_SENT'
  | 'ONBOARDING_LINK_OPENED'
  | 'ONBOARDING_SUBMITTED'
  | 'ONBOARDING_TOKEN_USED'
  | 'ONBOARDING_TOKEN_REVOKED'
  | 'APPOINTMENT_CONFIRM_TOKEN_USED'
  | 'APPOINTMENT_CANCEL_TOKEN_USED'
  | 'INVOICE_CREATED'
  | 'INVOICE_SENT'
  | 'INVOICE_PAID'
  | 'INVOICE_CANCELLED'
  | 'INVOICE_STORNO_CREATED'
  | 'INVOICE_EXPORTED'
  | 'EFACTURA_XML_GENERATED'
  | 'EFACTURA_SUBMITTED'
  | 'REPORT_FINALIZED'
  | 'SETTINGS_UPDATED'
  | 'THERAPIST_PROFILE_UPDATED'
  | 'BILLING_SETTINGS_UPDATED'
  | 'GOOGLE_CONNECTED'
  | 'GOOGLE_DISCONNECTED'
  | 'PASSWORD_CHANGED'
  | 'MFA_ENABLED'
  | 'MFA_DISABLED'
  | 'SESSION_EXPIRED'
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILED'
  | 'SUPPORT_ACCESS_GRANTED'
  | 'SUPPORT_ACCESS_REVOKED'

export type AuditEntityType =
  | 'client'
  | 'note'
  | 'document'
  | 'contract'
  | 'consent'
  | 'appointment'
  | 'assessment'
  | 'report'
  | 'invoice'
  | 'onboarding_link'

export interface AuditEventInput {
  action: AuditAction
  category: AuditCategory
  entityType?: AuditEntityType
  entityId?: string
  clientId?: string
  severity?: AuditSeverity
  status?: AuditStatus
  metadata?: Record<string, unknown>
  beforeSnapshot?: Record<string, unknown>
  afterSnapshot?: Record<string, unknown>
  actorRole?: 'THERAPIST' | 'ANONYMOUS' | 'SYSTEM'
  ipAddress?: string | null
  userAgent?: string | null
}
