import type { TherapistSettings } from "./settings-actions";

export const EMPTY_REMOTE_SETTINGS: TherapistSettings = {
  full_name: null,
  cif: null,
  cpr_code: null,
  iban: null,
  practice_name: null,
  practice_address: null,
  practice_phone: null,
  practice_email: null,
  practice_caen: null,
  default_session_price: 250,
  default_session_duration_minutes: 50,
  session_types_pricing: { "Ședință Individuală": 250 },
  currency: "RON",
  work_schedule: {
    monday: { enabled: true, start: "09:00", end: "18:00", break_start: "13:00", break_end: "14:00" },
    tuesday: { enabled: true, start: "09:00", end: "18:00", break_start: "13:00", break_end: "14:00" },
    wednesday: { enabled: true, start: "09:00", end: "18:00", break_start: "13:00", break_end: "14:00" },
    thursday: { enabled: true, start: "09:00", end: "18:00", break_start: "13:00", break_end: "14:00" },
    friday: { enabled: true, start: "09:00", end: "17:00", break_start: "13:00", break_end: "14:00" },
    saturday: { enabled: false, start: "10:00", end: "14:00", break_start: null, break_end: null },
    sunday: { enabled: false, start: "10:00", end: "14:00", break_start: null, break_end: null },
  },
  smartbill_username: null,
  smartbill_cif: null,
  twilio_account_sid: null,
  twilio_phone_number: null,
  cas_active: false,
  cas_contract_number: null,
  cas_county: null,
  has_pin: false,
  google_connected: false,
  google_token_expires_at: null,
};
